services:
  - type: web
    name: flask-qr-generator
    env: python
    buildCommand: ""
    startCommand: gunicorn --workers 4 --worker-class gthread --threads 2 --bind 0.0.0.0:10000 --timeout 120 wsgi:app
    plan: free
